version: '3'
services:
  fanty:
    depends_on:
      - mysql
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: fanty
    ports:
      - 80:80
      - 8081:8081
    environment:
      XDEBUG_HOST: ${XDEBUG_HOST}
    volumes:
      - ./app:/var/www/html
      - ./php/ini/php.ini:/etc/php/8.1/fpm/php.ini
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - fanty-docker
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - fanty-docker
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fanty
      MYSQL_USER: fanty
      MYSQL_PASSWORD: fanty
    networks:
      - fanty-docker
    volumes:
      - my-datavolume:/var/lib/mysql
networks:
  fanty-docker:
    external: true
volumes:
  redisdata:
    driver: "local"
  my-datavolume:


